#!/usr/bin/env python3

import os
import subprocess

import click

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")


@click.command()
@click.option("--replicas", required=False, default=1, type=int)
def main(replicas):
    click.echo("Enabling colours")
    subprocess.check_call(
        [
            KUBECTL,
            "create",
            "deploy",
            "colours",
            "--image",
            "ghcr.io/gdwr/colours:master",
            "--replicas",
            str(replicas),
        ]
    )
    click.echo("Enabled colours")


if __name__ == "__main__":
    main()
