#!/usr/bin/env python3

import os
import subprocess

import click

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")


@click.command()
def main():
    click.echo("Enabling colours")
    subprocess.check_call([KUBECTL, "apply", "-f", "colours.yaml"])
    click.echo("Enabled colours")


if __name__ == "__main__":
    main()
