#!/usr/bin/env python3

import os
import subprocess

import click


KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")


@click.command()
def main():
    current_path = os.path.dirname(os.path.realpath(__file__))
    manifest = f"{current_path}/colours.yaml"

    # Failures are ignored
    subprocess.check_call([KUBECTL, "create", "namespace", "gdwr"])

    click.echo("Enabling colours")
    subprocess.check_call([KUBECTL, "apply", "-f", manifest])
    click.echo("Enabled colours")


if __name__ == "__main__":
    main()
