#!/usr/bin/env python3

import click
import os
import subprocess

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")


@click.command()
def main():
    click.echo("Disabling grafana")
    subprocess.check_call([KUBECTL, "delete", "deploy", "grafana"])
    click.echo("Disabled grafana")


if __name__ == "__main__":
    main()
